### ISSUE TITLE
TypeError: Cannot read property 'environment' of undefined

### ISSUE THREAD

**Issue by jontstaz** [AquilaCMS/AquilaCMS#198]
Hi,

I have followed the instructions exactly but I keep facing this same error when I try to run the code. I have tried using yarn, npm, npm + PM2 and yarn + PM2 but I get the same error each time. Can you please let me know if I am missing a step somewhere? Is there anything that has been omitted from the README for any reason?

```
/!\ Unhandled rejection promise /!\ Promise {
  <rejected> TypeError: Cannot read property 'environment' of undefined
      at manageExceptionsRoutes (/home/ubuntu/AquilaCMS/routes/index.js:81:33)
      at Layer.handle [as handle_request] (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/layer.js:95:5)
      at next (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/route.js:144:13)
      at Route.dispatch (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/route.js:114:3)
      at Layer.handle [as handle_request] (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/layer.js:95:5)
      at /home/ubuntu/AquilaCMS/node_modules/express/lib/router/index.js:284:15
      at param (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/index.js:365:14)
      at param (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/index.js:376:14)
      at Function.process_params (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/index.js:421:3)
      at next (/home/ubuntu/AquilaCMS/node_modules/express/lib/router/index.js:280:10)
```

Thanks in advance,

**Comment by devaquila** [comment]
Thanks for your feedback !
Since our last release, this variable (aquila.environnement) has changed location, and in some cases, this was a problem.
We have generated a new release to fix that.
