### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by vivek4321** [AquilaCMS/AquilaCMS#208]
PS C:\Users\devel\Documents\code\AquilaCMS> npm run build

> aquila-cms@1.302.15c build
> node ./scripts/build default_theme

(node:22156) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: mongoose.Promise must be a function, got undefined
    at store.set (C:\Users\devel\Documents\code\AquilaCMS\node_modules\mongoose\lib\promise_provider.js:37:10)
    at Object.<anonymous> (C:\Users\devel\Documents\code\AquilaCMS\node_modules\mongoose\lib\promise_provider.js:47:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\devel\Documents\code\AquilaCMS\node_modules\mongoose\lib\helpers\promiseOrCallback.js:3:25)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\devel\Documents\code\AquilaCMS\node_modules\mongoose\lib\utils.js:19:27) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.12.1

**Comment by MaelVB** [comment]
Hi, thanks for the report.

This script was using an old way of doing things, we just updated it, feel free to try again!
